FROM node:24-alpine as development

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN npm install -g @nestjs/cli

COPY . .

ENV NODE_ENV=development

EXPOSE 4000

CMD ["npm", "run", "start:dev"]