// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "manifest": {
    "name": "Maf App"
  },
  "error": {
    "description": "<p>We've unfortunately encountered an error.</p><p>You can try to <retry>reload the page</retry> you were visiting.</p>",
    "title": "Something went wrong!"
  },
  "not-found-page": {
    "description": "Please double-check the browser address bar or use the navigation to go to a known page.",
    "title": "Page not found"
  },
  "navigation": {
    "about": "About us",
    "blog": "Blog",
    "calendar": "Calendar",
    "contacts": "Contacts",
    "players": "Players",
    "rating": "Rating",
    "tournaments": "Tournaments"
  },
  "locale-switcher": {
    "label": "Change language",
    "en": "English",
    "uk": "Ukrainian"
  },
  "index-page": {
    "title": "Home page"
  },
  "about-page": {
    "title": "About us page"
  },
  "calendar-page": {
    "title": "Calendar page"
  },
  "tournaments-page": {
    "title": "Tournaments page"
  },
  "players-page": {
    "title": "Players page"
  },
  "player-page": {
    "title": "Player page"
  },
  "rating-page": {
    "title": "Rating page"
  },
  "blog-page": {
    "title": "Blog page"
  },
  "contacts-page": {
    "title": "Contacts page"
  },
  "locale-layout": {
    "title": "Maf App"
  },
  "auth": {
    "login-title": "Sign in",
    "register-title": "Create an account",
    "username": "Nickname",
    "email": "Email",
    "password": "Password",
    "password-hint": "At least 8 characters, no spaces",
    "sign-in": "Sign in",
    "sign-up": "Sign up",
    "sign-out": "Sign out",
    "host-panel": "Host panel",
    "no-account": "No account yet?",
    "have-account": "Already have an account?",
    "errors": {
      "invalid_credentials": "Wrong email or password",
      "email_taken": "This email is already registered",
      "invalid_input": "Please check the form",
      "too_many_requests": "Too many attempts. Try again in a minute",
      "unknown": "Something went wrong. Try again later"
    }
  }
};
export default messages;